add_lunch_combo aokp_d2att-userdebug
add_lunch_combo aokp_d2spr-userdebug
add_lunch_combo aokp_d2tmo-userdebug
add_lunch_combo aokp_d2vzw-userdebug
add_lunch_combo aokp_manta-userdebug
add_lunch_combo aokp_p4wifi-userdebug
add_lunch_combo aokp_i777-userdebug


